apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: oidcclients.auth.hops.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: auth.hops.ops.com.ai/v1alpha1
    kind: OIDCClient
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-auth-stackoidcclient
    step: oidcclient
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
