apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: machineusers.auth.hops.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: auth.hops.ops.com.ai/v1alpha1
    kind: MachineUser
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-auth-stackmachineuser
    step: machineuser
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
