apiVersion: hops.ops.com.ai/v1alpha1
kind: AuthStack
metadata:
  name: auth
  namespace: example-env
spec:
  clusterName: example-cluster
  domain: auth.example.com
  firstInstance:
    masterkey:
      secretRef:
        name: zitadel-masterkey
  database:
    external:
      dsnSecretRef:
        name: zitadel-db
        key: dsn
